name: main branch auto ci process script

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest # 실행될 인스턴스 OS와 버전

    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.6 # ssh 접속하는 오픈소스
        with:
          host: ${{ secrets.REMOTE_IP }} # 인스턴스 IP
          username: ${{ secrets.REMOTE_USER }} # 우분투 아이디
          password: ${{ secrets.REMOTE_PASSWORD }} # ec2 instance password
          port: ${{ secrets.REMOTE_SSH_PORT }} # 접속포트
          script: | # 실행할 스크립트
            cd /home/jangdu/next_community
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            nvm use v18.15.0
            git pull origin main
            cd community_client
            npm i --force
            npm run build:prod
            cd /home/jangdu/next_community/community_server
            npm i --force
            pm2 reload all
            
