name: main branch auto ci process script

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest # 실행될 인스턴스 OS와 버전
    strategy:
      matrix:
        node-versions: [18.x]

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2

      - name: Install Dependencies and Build
        run: |
          cd community_client
          npm install --force
          npm run build:prod

      - name: Copy files to remote server
        run: |
          ssh-keyscan -H ${{ secrets.REMOTE_IP }} >> ~/.ssh/known_hosts
          scp -r build ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_IP }}:/home/jangdu/next_community

      - name: Deploy to remote server
        uses: appleboy/ssh-action@v0.1.6
        with:
          strict-host-key-checking: false
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /home/jangdu/next_community/community_client && pm2 delete comu-server || : && pm2 start ecosystem.config.js
            cd /home/jangdu/next_community/community_server && npm install --force
            cd /home/jangdu/next_community/community_server && pm2 delete comu-server || : && pm2 start ecosystem.config.js
