name: main branch auto ci process script

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest # 실행될 인스턴스 OS와 버전
    strategy:
      matrix:
        node-versions: [18.x]

    steps:
      - name: Checkout soure code.
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          cd community_client
          npm install --force
          npm run build:prod
          
      - name: Add SSH key to known_hosts
        run: ssh-keyscan -H ${{ secrets.REMOTE_IP }} >> ~/.ssh/known_hosts
          
      - name: Deploy to remote server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_IP }} 'cd /home/jangdu/next_community && rm -rf *'
            scp -r ./build ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_IP }}:/home/jangdu/next_community
            ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_IP }} 'cd /home/jangdu/next_community/community_client && pm2 delete comu-server || : && pm2 start ecosystem.config.js'
            ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_IP }} 'cd /home/jangdu/next_community/community_server && npm install -force'
            ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_IP }} 'cd /home/jangdu/next_community/community_server && pm2 delete comu-server || : && pm2 start ecosystem.config.js'
            
